title: Rebecca Robinson Chavez 
description: Resume
url: https://rebeja.github.io/jekyll-cv/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml

